# Generated by Django 6.0.7 on 2026-07-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_campaignrecipient_replied_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignrecipient',
            name='message_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='thread_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='campaignrecipient',
            name='replied_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
