# Generated by Django 6.0.7 on 2026-07-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_campaignrecipient_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='meeting',
            name='google_meet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
