# Generated by Django 6.0.7 on 2026-07-24 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_meeting_duration_minutes_meeting_google_meet_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='parent_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.campaign'),
        ),
    ]
